### ISSUE TITLE
error about running dataset(openproblems_bmmc_cite_phase2 ) with scMoGCN

### ISSUE THREAD

**Issue by yuxiaokang-source** [OmicsML/dance#245]
After I installed dance, I run  `python scmogcn.py --subtask openproblems_bmmc_cite_phase2 --device cuda`, but I found code have this error
<img width="441" alt="image" src="https://user-images.githubusercontent.com/59059267/228832388-fa49eef9-efca-4fa2-9113-5e79a8949702.png">
, `AddReverse` is occurred on the 125 line of  `cell_feature_graph.py`, It should be a function of dgl, but it was not imported

**Comment by RemyLau** [comment]
Thanks you for the catch! This should have been fixed by now.
