### ISSUE TITLE
Running scmogcn.py example - fatal error

### ISSUE THREAD

**Issue by valtado1** [OmicsML/dance#257]
Hello,

I am trying to reproduce the scmogcn.py example from the DANCE documentation. I run this script:
<img width="556" alt="Screenshot 2023-04-19 at 6 47 49 PM" src="https://user-images.githubusercontent.com/89887190/233216062-fc20fa87-ad94-4a95-850b-f0980d267966.png">

in the same folder where scmogcn.py is located. I'm using MSU's HPCC and a conda environment. After submitting the job, my slurm file gives this error: "dgl._ffi.base.DGLError: [18:00:11] /opt/dgl/src/random/random.cc:36: Check failed: e == CURAND_STATUS_SUCCESS: CURAND Error: CURAND_STATUS_INITIALIZATION_FAILED at /opt/dgl/src/random/random.cc:36"

Do you know what I might be doing wrong or how I can fix this error so that I can successfully reproduce this example?

**Comment by RemyLau** [comment]
Could you make sure you have activated the correct environment where you installed the dance package? Here, it seems like you are using the base environment, which works if you did install dance in the base, but is not recommended.
