### ISSUE TITLE
pip install pydance

### ISSUE THREAD

**Issue by schwartznicholas** [OmicsML/dance#258]
When running pip install pydance on a local environment running on an M1 macbook air, the following exception is raised. I believe the issue stems from "tables":

<img width="1419" alt="Screenshot 2023-04-21 at 3 41 29 PM" src="https://user-images.githubusercontent.com/77458683/233721801-0b18bcff-1c5b-4d0f-adbd-737c051b29dd.png">

**Comment by RemyLau** [comment]
Seems like an issue with installing hdf5 on M1 Mac. This issue seems to be resolved by: https://stackoverflow.com/questions/66741778/how-to-install-h5py-needed-for-keras-on-macos-with-m1
