### ISSUE TITLE
Questions about conda installing

### ISSUE THREAD

**Issue by HelloWorldLTY** [OmicsML/dance#354]
Hi, I have a question about conda installing process:

![image](https://github.com/OmicsML/dance/assets/43333475/07526197-2505-49ee-9413-71347ca09111)

I think we should use 
```
conda activate dance
```

rather than

```
conda activate dance-env
```
Is it correct? Thanks.

**Comment by RemyLau** [comment]
Hi @HelloWorldLTY, that is correctly. We should indeed `conda activate dance` instead. Thank you for catching the typo!
