### ISSUE TITLE
libcusparse.so.11

### ISSUE THREAD

**Issue by arashyunesi** [OmicsML/dance#436]
I followed the install.sh file to install dance in a conda env. Now I am following the tutorial. I am getting this error 
"OSError: libcusparse.so.11: cannot open shared object file: No such file or directory"
when running 
"from dance.datasets.singlemodality import ClusteringDataset"
I don't know where the issue is coming from. I appreciate any suggestions.

**Comment by wehos** [comment]
Duplicate with this [issue](https://github.com/OmicsML/dance/issues/431).

**Comment by arashyunesi** [comment]
I added "export LD_LIBRARY_PATH=/path/to/lib" to the .bashrc file and restarted the kernel it worked. Another option is to avoid overwriting previous LD_LIBRARY path by adding "export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/path/to/lib" instead. Thank you @wehos
